import { jsPDF } from 'jspdf'

// ─── Shared PDF Helpers ──────────────────────────────────────────────────────
const drawPageBorder = (d) => {
  // Border removed per design requirements
  return d
}

const drawHeaderFooter = (d, titleStr, pageNum) => {
  drawPageBorder(d)
  
  // Subtle watermark background
  d.setFont('Helvetica', 'bold')
  d.setFontSize(28)
  d.setTextColor(245, 247, 250) // Extremely light gray
  d.text('GENERATED BY SYLLABIX', 105, 150, { angle: 45, align: 'center' })

  // Header text
  d.setFont('Helvetica', 'normal')
  d.setFontSize(8)
  d.setTextColor(100, 116, 139)
  d.text('SYLLABIX', 15, 20)
  d.text('AI CURRICULUM GENERATOR', 195, 20, { align: 'right' })
  
  d.setDrawColor(226, 232, 240)
  d.setLineWidth(0.25)
  d.line(15, 22, 195, 22)

  // Footer text
  d.line(15, 280, 195, 280)
  
  const today = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  d.text(`GENERATED BY SYLLABIX  ·  ${today.toUpperCase()}`, 15, 285)
  d.text(`PAGE ${pageNum}`, 195, 285, { align: 'right' })
}

class DocumentCursor {
  constructor(d, titleStr) {
    this.doc = d
    this.title = titleStr
    this.margin = 15
    this.width = 180
    this.y = 28
    this.pageNum = 1
  }

  addPage() {
    this.doc.addPage()
    this.pageNum++
    this.y = 28
    drawHeaderFooter(this.doc, this.title, this.pageNum)
  }

  newPage() {
    this.addPage()
  }

  checkSpace(heightNeeded) {
    if (this.y + heightNeeded > 278) {
      this.addPage()
    }
  }

  writeTitle(text) {
    this.checkSpace(22)
    this.doc.setFont('Helvetica', 'bold')
    this.doc.setFontSize(19)
    this.doc.setTextColor(91, 95, 239) // Brand color
    this.doc.text(text.toUpperCase(), this.margin, this.y)
    this.y += 12
  }

  writeSubHeader(text) {
    this.checkSpace(18)
    this.doc.setFont('Helvetica', 'bold')
    this.doc.setFontSize(13.5)
    this.doc.setTextColor(15, 23, 42) // Dark Slate
    this.doc.text(text, this.margin, this.y)
    this.y += 9
  }

  writeParagraph(text) {
    this.doc.setFont('Helvetica', 'normal')
    this.doc.setFontSize(11)
    this.doc.setTextColor(64, 74, 86)
    const lines = this.doc.splitTextToSize(text, this.width)
    const neededHeight = lines.length * 5.5 + 3
    this.checkSpace(neededHeight)
    this.doc.text(text, this.margin, this.y, { align: 'justify', maxWidth: this.width })
    this.y += neededHeight
  }

  writeBullet(text) {
    this.doc.setFont('Helvetica', 'normal')
    this.doc.setFontSize(11)
    this.doc.setTextColor(64, 74, 86)
    const bulletSymbol = '•'
    const textIndent = 5
    const textWidth = this.width - textIndent
    const lines = this.doc.splitTextToSize(text, textWidth)
    const neededHeight = lines.length * 5.5 + 2
    this.checkSpace(neededHeight)

    this.doc.text(bulletSymbol, this.margin, this.y)
    this.doc.text(text, this.margin + textIndent, this.y, { align: 'justify', maxWidth: textWidth })
    this.y += neededHeight
  }
}

const drawTable = (d, startY, headers, rows, colWidths, margin = 15) => {
  let y = startY
  const totalWidth = colWidths.reduce((a, b) => a + b, 0)
  const scaleFactor = 180 / totalWidth
  const scaledColWidths = colWidths.map(w => w * scaleFactor)
  const scaledTotalWidth = 180
  
  // Header row
  d.setFillColor(91, 95, 239)
  d.setDrawColor(91, 95, 239)
  d.rect(margin, y, scaledTotalWidth, 10, 'F')
  
  let x = margin
  d.setFont('Helvetica', 'bold')
  d.setFontSize(11.5)
  d.setTextColor(255, 255, 255)
  headers.forEach((h, idx) => {
    d.text(h, x + 2.5, y + 6.5)
    x += scaledColWidths[idx]
  })
  y += 10
  
  // Rows
  d.setFont('Helvetica', 'normal')
  d.setFontSize(11)
  
  rows.forEach((row, rIdx) => {
    let maxLines = 1
    const splitTexts = row.map((cell, idx) => {
      const cellText = String(cell || '')
      const lines = d.splitTextToSize(cellText, scaledColWidths[idx] - 4)
      if (lines.length > maxLines) maxLines = lines.length
      return lines
    })
    
    const rowHeight = maxLines * 5.5 + 4
    
    // Page break check inside tables
    if (y + rowHeight > 278) {
      d.addPage()
      // Draw layout border on new page
      drawPageBorder(d)
      y = 28
      
      // Repeat table headers
      d.setFillColor(91, 95, 239)
      d.rect(margin, y, scaledTotalWidth, 10, 'F')
      let rx = margin
      d.setFont('Helvetica', 'bold')
      d.setFontSize(11.5)
      d.setTextColor(255, 255, 255)
      headers.forEach((h, idx) => {
        d.text(h, rx + 2.5, y + 6.5)
        rx += scaledColWidths[idx]
      })
      y += 10
      d.setFont('Helvetica', 'normal')
      d.setFontSize(11)
    }
    
    // Zebra shading
    if (rIdx % 2 === 1) {
      d.setFillColor(248, 250, 252)
      d.rect(margin, y, scaledTotalWidth, rowHeight, 'F')
    }
    
    let rx = margin
    splitTexts.forEach((lines, idx) => {
      d.setDrawColor(226, 232, 240)
      d.setLineWidth(0.2)
      d.rect(rx, y, scaledColWidths[idx], rowHeight)
      
      d.setTextColor(64, 74, 86)
      lines.forEach((line, lineIdx) => {
        d.text(line, rx + 2.5, y + 5 + lineIdx * 5.5)
      })
      rx += scaledColWidths[idx]
    })
    
    y += rowHeight
  })
  
  return y
}

const drawUnitCard = (cursor, unit) => {
  cursor.checkSpace(100)
  const cardStartY = cursor.y
  const width = cursor.width
  const margin = cursor.margin
  
  // Header block
  cursor.doc.setFillColor(248, 250, 252)
  cursor.doc.rect(margin, cardStartY, width, 12, 'F')
  cursor.doc.setDrawColor(226, 232, 240)
  cursor.doc.setLineWidth(0.4)
  cursor.doc.rect(margin, cardStartY, width, 12)
  
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(13)
  cursor.doc.setTextColor(91, 95, 239)
  cursor.doc.text(`UNIT ${unit.unit_number || unit.id || ''}: ${unit.name.toUpperCase()}`, margin + 3, cardStartY + 8.5)
  
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(100, 116, 139)
  cursor.doc.text(`Bloom: ${unit.blooms_taxonomy || 'Understanding'}`, margin + width - 3, cardStartY + 8.5, { align: 'right' })
  
  // Draw justified unit description
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(64, 74, 86)
  
  const descText = unit.description || 'This module covers core concepts and industry applications.'
  const descLines = cursor.doc.splitTextToSize(descText, width - 6)
  const descHeight = descLines.length * 5 + 3
  
  cursor.doc.text(descText, margin + 3, cardStartY + 18, { align: 'justify', maxWidth: width - 6 })
  
  // Columns start below description
  const contentStartY = cardStartY + 18 + descHeight
  cursor.y = contentStartY
  
  const gap = 8
  const colWidth = (width - gap) / 2
  
  // Left side: topics & labs
  let leftY = contentStartY
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(11)
  cursor.doc.setTextColor(15, 23, 42)
  cursor.doc.text('Syllabus Topics Covered:', margin + 3, leftY)
  leftY += 6
  
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(64, 74, 86)
  const topics = unit.topics || []
  topics.forEach((t, idx) => {
    const textStr = `${idx + 1}. ${t}`
    const lines = cursor.doc.splitTextToSize(textStr, colWidth - 6)
    lines.forEach(l => {
      cursor.doc.text(l, margin + 5, leftY)
      leftY += 5
    })
  })
  
  leftY += 4
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(11)
  cursor.doc.setTextColor(15, 23, 42)
  cursor.doc.text('Practical Labs & Activities:', margin + 3, leftY)
  leftY += 6
  
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(64, 74, 86)
  const activities = unit.practice_activities || []
  activities.forEach(act => {
    const lines = cursor.doc.splitTextToSize(`• ${act}`, colWidth - 6)
    lines.forEach(l => {
      cursor.doc.text(l, margin + 5, leftY, { align: 'justify', maxWidth: colWidth - 6 })
      leftY += 5
    })
  })
  
  // Right side: outcomes, assessments & resources
  let rightY = contentStartY
  const rightX = margin + colWidth + gap
  
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(11)
  cursor.doc.setTextColor(15, 23, 42)
  cursor.doc.text('Learning Outcomes:', rightX + 3, rightY)
  rightY += 6
  
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(64, 74, 86)
  const outcomes = unit.learning_outcomes || []
  outcomes.forEach(lo => {
    const lines = cursor.doc.splitTextToSize(`• ${lo}`, colWidth - 6)
    lines.forEach(l => {
      cursor.doc.text(l, rightX + 5, rightY, { align: 'justify', maxWidth: colWidth - 6 })
      rightY += 5
    })
  })
  
  rightY += 4
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(11)
  cursor.doc.setTextColor(15, 23, 42)
  cursor.doc.text('Assignments & Rubrics:', rightX + 3, rightY)
  rightY += 6
  
  cursor.doc.setFont('Helvetica', 'normal')
  cursor.doc.setFontSize(10)
  cursor.doc.setTextColor(64, 74, 86)
  const assessments = unit.assessments || []
  assessments.forEach(ass => {
    const lines = cursor.doc.splitTextToSize(`• ${ass}`, colWidth - 6)
    lines.forEach(l => {
      cursor.doc.text(l, rightX + 5, rightY, { align: 'justify', maxWidth: colWidth - 6 })
      rightY += 5
    })
  })

  // Recommended Resources
  rightY += 4
  cursor.doc.setFont('Helvetica', 'bold')
  cursor.doc.setFontSize(11)
  cursor.doc.setTextColor(15, 23, 42)
  cursor.doc.text('Recommended Resources:', rightX + 3, rightY)
  rightY += 6

  cursor.doc.setFontSize(9)
  const res = unit.resources || {}
  
  const drawLinkResource = (label, name, url) => {
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setTextColor(64, 74, 86)
    cursor.doc.text(`${label}: `, rightX + 5, rightY)
    const labelWidth = cursor.doc.getTextWidth(`${label}: `)
    
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setTextColor(91, 95, 239)
    
    const maxLinkWidth = colWidth - 5 - labelWidth
    const displayName = name || 'Resource Link'
    const wrappedLink = cursor.doc.splitTextToSize(displayName, maxLinkWidth)
    
    wrappedLink.forEach((l) => {
      if (url) {
        cursor.doc.textWithLink(l, rightX + 5 + labelWidth, rightY, { url })
      } else {
        cursor.doc.text(l, rightX + 5 + labelWidth, rightY)
      }
      rightY += 4.5
    })
  }

  if (res.book) {
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setTextColor(64, 74, 86)
    cursor.doc.text('Book: ', rightX + 5, rightY)
    const labelWidth = cursor.doc.getTextWidth('Book: ')
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setTextColor(100, 116, 139)
    const bLines = cursor.doc.splitTextToSize(res.book, colWidth - 5 - labelWidth)
    bLines.forEach(l => {
      cursor.doc.text(l, rightX + 5 + labelWidth, rightY)
      rightY += 4.5
    })
  }
  if (res.youtube && res.youtube.url) {
    drawLinkResource('Video', res.youtube.name, res.youtube.url)
  }
  if (res.google && res.google.url) {
    drawLinkResource('Doc', res.google.name, res.google.url)
  }
  if (res.research_paper && res.research_paper.url) {
    drawLinkResource('Research', res.research_paper.name, res.research_paper.url)
  }
  if (res.github && res.github.url) {
    drawLinkResource('Code', res.github.name, res.github.url)
  }
  
  const maxEndY = Math.max(leftY, rightY) + 4
  
  // Draw outer boundary and column divider lines
  cursor.doc.setDrawColor(226, 232, 240)
  cursor.doc.setLineWidth(0.4)
  cursor.doc.rect(margin, cardStartY, width, maxEndY - cardStartY)
  cursor.doc.line(margin + colWidth + gap/2, contentStartY, margin + colWidth + gap/2, maxEndY)
  
  cursor.y = maxEndY + 8
}

// ─── Main Exporters ──────────────────────────────────────────────────────────

export const downloadCurriculumPDF = async (curriculum) => {
  if (!curriculum) throw new Error('No curriculum data provided')

  const { 
    program_name, education_level, industry_focus, program_duration, semesters, 
    stats, capstone_project, 
    tech_coverage, program_objectives, career_paths, certifications, skill, curriculum_type,
    weekly_hours
  } = curriculum

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // ---------------- PAGE 1: COVER PAGE ----------------
  drawPageBorder(doc)

  // Top Accent Band
  doc.setFillColor(91, 95, 239)
  doc.rect(15, 15, 180, 5, 'F')

  // Document Type / Header
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text('ACADEMIC SYLLABUS & CURRICULUM HANDBOOK', 25, 40)

  // Title
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(32)
  doc.setTextColor(15, 23, 42)
  doc.text('SYLLABUS', 25, 55)
  doc.text('FRAMEWORK', 25, 68)

  // Subtitle
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.text('Official Curriculum Accreditation Standards & Guidelines', 25, 76)

  // Accent Line
  doc.setDrawColor(91, 95, 239)
  doc.setLineWidth(0.8)
  doc.line(25, 82, 75, 82)

  // Program Specifications Title
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('PROGRAM SPECIFICATIONS', 25, 93)

  // --- Audit Comment: Stacked Metadata Specs Box ---
  // Renders a styled rectangle enclosing course details.
  // Values are rendered vertically stacked underneath their respective uppercase labels.
  // Columns are split at x = 25 and x = 115 with row spacing of 13mm to prevent overlapping.
  const specBoxY = 98
  doc.setFillColor(248, 250, 252)
  doc.rect(15, specBoxY, 180, 58, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.rect(15, specBoxY, 180, 58)

  const metaRows = [
    { label: 'Course Title', value: program_name },
    { label: 'Education Level', value: education_level },
    { label: 'Curriculum Type', value: curriculum_type || 'Theory + Practical' },
    { label: 'Industry Domain', value: industry_focus },
    { label: 'Program Duration', value: program_duration },
    { label: 'Total Workload', value: `${weekly_hours} Hours/Week` },
    { label: 'Total Semesters', value: `${semesters.length} Semesters` },
    { label: 'Total Credits', value: `${stats?.totalCredits || 0} Credits` }
  ]

  metaRows.forEach((row, idx) => {
    const col = idx < 4 ? 0 : 1
    const rowInCol = idx % 4
    const x = col === 0 ? 25 : 115
    const yVal = specBoxY + 6.5 + (rowInCol * 13)

    // Print Label
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(100, 116, 139)
    doc.text(row.label.toUpperCase(), x, yVal)

    // Print Value
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(15, 23, 42)
    const valText = String(row.value)
    const valLines = doc.splitTextToSize(valText, 70)
    valLines.forEach((line, lineIdx) => {
      doc.text(line, x, yVal + 4.5 + (lineIdx * 3.5))
    })
  })

  // Executive Summary Section
  const summaryY = 168
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('EXECUTIVE SUMMARY', 15, summaryY)

  // Accent Line for Summary
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(15, 172, 195, 172)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(64, 74, 86)
  const summaryText = `This handbook defines the comprehensive curriculum, academic milestones, and course outlines for the ${program_name} program. Structured to support a weekly workload of ${weekly_hours} hours over a timeline of ${program_duration}, the syllabus balances theoretical core concepts with intensive practical labs and milestone projects. The program aims to equip graduates with core competencies in ${skill || 'targeted domains'} directly mapped to standard practices and demands of the ${industry_focus} sector.`
  doc.text(summaryText, 15, 178, { align: 'justify', maxWidth: 180 })

  // Footer branding on cover page
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('SYLLABIX ACADEMIC HANDBOOK SYSTEM', 15, 280)
  doc.text(new Date().toLocaleDateString().toUpperCase(), 195, 280, { align: 'right' })

  // ---------------- PAGE 2: TABLE OF CONTENTS ----------------
  const cursor = new DocumentCursor(doc, program_name)
  cursor.newPage()

  cursor.writeTitle('Table of Contents')
  cursor.writeParagraph('This handbook is organized into the following chapters mapped to academic syllabus audits:')
  cursor.y += 6

  const tocEntries = [
    { title: '1. Program Overview & Introduction', page: 3 },
    { title: '2. Educational Objectives & Outcomes', page: 3 },
    { title: '3. Academic Curriculum Breakdown', page: 4 },
    ...semesters.map(s => ({ title: `   · Semester ${s.semester_number}: Timeline Outline`, page: 3 + s.semester_number })),
    { title: '4. Evaluation & Rubric Strategy', page: 4 + semesters.length },
    { title: '5. Academic Resources Handbook', page: 5 + semesters.length },
    { title: '6. Skill Mapping Competency Index', page: 6 + semesters.length },
    { title: '7. Career Opportunities & Placements', page: 7 + semesters.length },
    { title: '8. Final Program Competency Outcomes', page: 8 + semesters.length }
  ]

  tocEntries.forEach(entry => {
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(9)
    cursor.doc.setTextColor(64, 74, 86)
    cursor.doc.text(entry.title, cursor.margin, cursor.y)

    const tWidth = cursor.doc.getTextWidth(entry.title)
    const dotStart = cursor.margin + tWidth + 3
    const dotEnd = 185
    let dots = ''
    let dX = dotStart
    while (dX < dotEnd) {
      dots += '.'
      dX += 1.8
    }
    cursor.doc.text(dots, dotStart, cursor.y)

    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.text(`Page ${entry.page}`, 195, cursor.y, { align: 'right' })
    cursor.y += 8
  })

  // ---------------- PAGE 3: PROGRAM OVERVIEW ----------------
  cursor.newPage()
  cursor.writeTitle('Program Overview & Objectives')

  cursor.writeSubHeader('Program Summary')
  cursor.writeParagraph(`The ${program_name} is an academic curriculum framework structured to introduce core and specialized topics in ${skill || 'Target Domain'}. This curriculum framework bridges critical theoretical paradigms and practical application loops to establish absolute alignment with technologies inside the ${industry_focus} sector. Students participate in standard weekly study workloads of ${weekly_hours} hours over a timeline of ${program_duration}.`)

  cursor.writeSubHeader('Target Audience')
  cursor.writeParagraph(`This curriculum framework is optimized for aspiring engineering students, computer specialists, and workspace developers seeking to master the principles of ${skill} and apply them to target industrial situations.`)

  cursor.writeSubHeader('Industry Relevance & Alignment')
  cursor.writeParagraph(`The syllabus modules directly match developer requirements in the ${industry_focus} sector. Topics cover standard practices and map tools like ${tech_coverage.join(', ')} to resolve identified workspace skill gaps.`)

  cursor.writeSubHeader('Program Objectives')
  program_objectives.forEach(obj => {
    cursor.writeBullet(obj)
  })

  // ---------------- PAGES 4+: SEMESTERS ----------------
  semesters.forEach(sem => {
    cursor.newPage()
    
    // Semester Header Banner box
    const hdrY = cursor.y
    doc.setFillColor(91, 95, 239)
    doc.rect(cursor.margin, hdrY, cursor.width, 14, 'F')
    
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(11.5)
    doc.setTextColor(255, 255, 255)
    doc.text(`SEMESTER ${sem.semester_number}: ${sem.theme.toUpperCase()}`, cursor.margin + 4, hdrY + 5.5)

    doc.setFont('Helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.text(`Credits: ${sem.credits} Academic Credits  |  Workload Commit: ${weekly_hours} hrs/week  |  Composition: 5 Units`, cursor.margin + 4, hdrY + 10)

    cursor.y = hdrY + 22

    cursor.writeSubHeader('Semester Learning Outcomes')
    sem.learning_outcomes.forEach(lo => {
      cursor.writeBullet(lo)
    })
    cursor.y += 3

    cursor.writeSubHeader('Unit TIMELINE & Roadmap')
    sem.units.forEach(unit => {
      drawUnitCard(cursor, unit)
    })
  })

  // ---------------- PAGE: ACCREDITATION ASSESSMENT RUBRICS ----------------
  cursor.newPage()
  cursor.writeTitle('Evaluation & Rubric Strategy')
  cursor.writeParagraph('To ensure full compliance with accreditation bodies, candidate performance is evaluated through continuous diagnostic audits and cumulative milestones:')
  cursor.y += 4

  const assessmentHeaders = ['Evaluation Component', 'Weightage %', 'Aims & Targeted Core Competency']
  const assessmentRows = [
    ['Weekly Quizzes', '10%', 'Baseline theoretical checks, vocabulary drills, and multiple-choice syntax diagnostics.'],
    ['Assignments', '30%', 'Coding exercises, mathematical proofs, runtime audits, and system profiling tasks.'],
    ['Lab Work & Tasks', '30%', 'Containerized sandbox test configurations, automated unit test delivery, and deployments.'],
    ['Milestone Projects', '30%', 'Semester milestone implementations checked against Bloom\'s taxonomy rubrics.'],
    ['Capstone Project', 'Evaluation Grade', `Full-scale system deployment: "${capstone_project.title}" validation.`]
  ]
  cursor.y = drawTable(doc, cursor.y, assessmentHeaders, assessmentRows, [45, 30, 105], cursor.margin)

  // ---------------- PAGE: RECOMMENDED RESOURCES HANDBOOK ----------------
  const books = []
  const videos = []
  const docs = []
  const research = []
  const codebases = []

  semesters.forEach(sem => {
    sem.units.forEach(unit => {
      const res = unit.resources || {}
      if (res.book && !books.includes(res.book)) {
        books.push(res.book)
      }
      if (res.youtube && res.youtube.url && !videos.some(v => v.url === res.youtube.url)) {
        videos.push(res.youtube)
      }
      if (res.google && res.google.url && !docs.some(d => d.url === res.google.url)) {
        docs.push(res.google)
      }
      if (res.research_paper && res.research_paper.url && !research.some(r => r.url === res.research_paper.url)) {
        research.push(res.research_paper)
      }
      if (res.github && res.github.url && !codebases.some(c => c.url === res.github.url)) {
        codebases.push(res.github)
      }
    })
  })

  cursor.newPage()
  cursor.writeTitle('Academic Resources Handbook')
  cursor.writeParagraph('This handbook compiles the recommended reference resources, official documentation guides, video series, and research databases required for this program. Click the resource titles to open direct digital web references.')
  cursor.y += 4

  const writeCategoryHeader = (title) => {
    cursor.checkSpace(18)
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(12)
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(title.toUpperCase(), cursor.margin, cursor.y)
    cursor.y += 5
    cursor.doc.setDrawColor(226, 232, 240)
    cursor.doc.setLineWidth(0.4)
    cursor.doc.line(cursor.margin, cursor.y, cursor.margin + cursor.width, cursor.y)
    cursor.y += 5
  }

  if (books.length > 0) {
    writeCategoryHeader('1. Core Textbooks & References')
    books.forEach(b => {
      cursor.writeBullet(b)
    })
    cursor.y += 4
  }

  if (videos.length > 0) {
    writeCategoryHeader('2. Video Lectures & Online Courses')
    videos.forEach(v => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(v.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(v.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: v.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  if (docs.length > 0) {
    writeCategoryHeader('3. Official Documentation & Guides')
    docs.forEach(d => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(d.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(d.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: d.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  if (research.length > 0) {
    writeCategoryHeader('4. Accredited Research Databases & Papers')
    research.forEach(r => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(r.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(r.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: r.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  writeCategoryHeader('5. Practice Portals & Code Playgrounds')
  const practiceLinks = [
    { name: 'LeetCode Placement Practice Platform', url: 'https://leetcode.com' },
    { name: 'HackerRank Academic Assessment Sandbox', url: 'https://hackerrank.com' }
  ]
  if (codebases.length > 0) {
    codebases.forEach(c => {
      practiceLinks.push({ name: `${c.name} (Source Repository)`, url: c.url })
    })
  }

  practiceLinks.forEach(p => {
    cursor.checkSpace(16)
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    cursor.doc.text('•  ', cursor.margin, cursor.y)
    
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(p.name, cursor.margin + 5, cursor.y)
    
    cursor.y += 4.5
    
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(9)
    cursor.doc.setTextColor(91, 95, 239)
    const wrappedUrl = cursor.doc.splitTextToSize(p.url, cursor.width - 5)
    wrappedUrl.forEach(l => {
      cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: p.url })
      cursor.y += 4
    })
    cursor.y += 2
  })
  cursor.y += 4

  // ---------------- PAGE: SKILL MAPPING MATRIX ----------------
  cursor.newPage()
  cursor.writeTitle('Skill Mapping Competency Index')
  cursor.writeParagraph('This index charts candidate skill development from foundational benchmarks to professional industry placement outcomes:')
  cursor.y += 4

  const skillHeaders = ['Category', 'Beginner Level', 'Intermediate Level', 'Advanced Level', 'Industry Ready']
  const skillRows = [
    ['Technical Core', 'Setup & terminal syntax rules', 'Function builds & DB loops', 'Threads, concurrency', 'Containerized deploys'],
    ['Architecture', 'Logic frameworks', 'Modular design flow', 'Microservices scaling', 'High-availability IaC'],
    ['QA & Testing', 'Manual execution', 'Automated unit tests', 'Profiling bottlenecks', 'CI/CD security scans'],
    ['Soft Skills', 'Comment lines & rules', 'Team milestone tasking', 'Technical briefs', 'Accreditation proposal audits']
  ]
  cursor.y = drawTable(doc, cursor.y, skillHeaders, skillRows, [32, 37, 37, 37, 37], cursor.margin)

  // ---------------- PAGE: CAREER OPPORTUNITIES ----------------
  cursor.newPage()
  cursor.writeTitle('Career Opportunities & Placements')
  cursor.writeParagraph('Graduates are fully prepared to secure high-demand tech sector roles with professional credentials:')
  cursor.y += 4

  const careerHeaders = ['Placements Roles', 'Required Technologies & Ecosystem', 'Target Accreditations']
  const careerRows = career_paths.map((role, idx) => {
    const cert = certifications[idx % certifications.length] || 'Google Cloud Architect'
    return [
      role,
      tech_coverage.slice(0, 4).join(', '),
      cert
    ]
  })
  cursor.y = drawTable(doc, cursor.y, careerHeaders, careerRows, [50, 68, 62], cursor.margin)

  // ---------------- PAGE: FINAL PROGRAM OUTCOMES ----------------
  cursor.newPage()
  cursor.writeTitle('Final Program Competency Outcomes')

  cursor.writeSubHeader('Technical Competencies')
  cursor.writeParagraph(`Graduates demonstrate absolute mastery over the ${skill} domain. They can design end-to-end sandbox systems, resolve system latency bottlenecks, write container scripts, and audit algorithms.`)

  cursor.writeSubHeader('Industry Readiness')
  cursor.writeParagraph(`Prepared to step directly into the corporate environment of the ${industry_focus} sector. Fully equipped with version control protocols, automated tests, and agile development loops.`)

  cursor.writeSubHeader('Capstone Preparation')
  cursor.writeParagraph(`Syllabus criteria are validated through the successful delivery of the Milestone Projects and the Capstone Project: "${capstone_project.title}". Deliverables demonstrate a Dockerized API ready for cloud distribution.`)

  cursor.writeSubHeader('Certification Readiness')
  cursor.writeParagraph(`Program outcomes map directly to major cloud and software credentials. Graduates are prepared to pass certification tests including: ${certifications.join(', ')}.`)

  // Return generated PDF object for preview/download workflow
  const filename = `${program_name.replace(/\s+/g, '_')}_Academic_Syllabus.pdf`
  return { doc, filename }
}

export const downloadStudentBlueprintPDF = async (curriculum, studentName) => {
  if (!curriculum) throw new Error('No curriculum data provided')

  const { 
    program_name, education_level, industry_focus, program_duration, semesters, 
    skill, weekly_hours, program_objectives, career_paths
  } = curriculum

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // ---------------- PAGE 1: COVER PAGE ----------------
  drawPageBorder(doc)

  // Top Accent Band
  doc.setFillColor(91, 95, 239)
  doc.rect(15, 15, 180, 5, 'F')

  // Document Type / Header
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text('PERSONALIZED LEARNING PATH & STUDY GUIDE', 25, 40)

  // Title
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(32)
  doc.setTextColor(15, 23, 42)
  doc.text('STUDY', 25, 55)
  doc.text('BLUEPRINT', 25, 68)

  // Subtitle
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.text('Structured Study Timeline & Learning Milestones', 25, 76)

  // Accent Line
  doc.setDrawColor(91, 95, 239)
  doc.setLineWidth(0.8)
  doc.line(25, 82, 75, 82)

  // Program Specifications Title
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('STUDY SPECIFICATIONS', 25, 93)

  // Draw metadata in a structured layout
  const specBoxY = 98
  doc.setFillColor(248, 250, 252)
  doc.rect(15, specBoxY, 180, 58, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.rect(15, specBoxY, 180, 58)

  const metaRows = [
    { label: 'Student Name', value: studentName },
    { label: 'Course Title', value: program_name },
    { label: 'Education Level', value: education_level },
    { label: 'Domain/Skill', value: skill },
    { label: 'Study Strategy', value: `${industry_focus} Applications` },
    { label: 'Weekly Commitment', value: `${weekly_hours} Hours/Week` },
    { label: 'Study Duration', value: program_duration },
    { label: 'Generation Date', value: new Date().toLocaleDateString() }
  ]

  metaRows.forEach((row, idx) => {
    const col = idx < 4 ? 0 : 1
    const rowInCol = idx % 4
    const x = col === 0 ? 25 : 115
    const yVal = specBoxY + 6.5 + (rowInCol * 13)

    // Print Label
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(100, 116, 139)
    doc.text(row.label.toUpperCase(), x, yVal)

    // Print Value
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(15, 23, 42)
    const valText = String(row.value)
    const valLines = doc.splitTextToSize(valText, 70)
    valLines.forEach((line, lineIdx) => {
      doc.text(line, x, yVal + 4.5 + (lineIdx * 3.5))
    })
  })

  // Executive Summary Section
  const summaryY = 168
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('EXECUTIVE STUDY SUMMARY', 15, summaryY)

  // Accent Line for Summary
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(15, 172, 195, 172)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(64, 74, 86)
  const summaryText = `This personalized study blueprint outlines the academic curriculum path designed for ${studentName}. By following the sequenced semesters, units, and day-wise study planners, you will build robust competency in the ${skill} domain with a specific specialization in ${industry_focus} integrations. Each module lists targeted learning outcomes, recommended textbooks, and online resources to ensure absolute readiness for certifications and placements.`
  doc.text(summaryText, 15, 178, { align: 'justify', maxWidth: 180 })

  // Footer branding on cover page
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('SYLLABIX LEARNER SYSTEM  ·  OFFICIAL BLUEPRINT', 15, 280)
  doc.text(new Date().toLocaleDateString().toUpperCase(), 195, 280, { align: 'right' })

  // Render semesters sequential details
  const cursor = new DocumentCursor(doc, `STUDY BLUEPRINT: ${program_name}`)

  // ---------------- PAGE 2: OBJECTIVES & CAREER PATHS ----------------
  cursor.newPage()
  cursor.writeTitle('Study Plan Objectives')
  cursor.writeParagraph(`Welcome, ${studentName}. This personalized study blueprint outlines your academic curriculum path. By following the sequenced semesters below, you will build core competency in the "${skill}" domain, specializing in "${industry_focus}" integrations.`)
  cursor.y += 4

  cursor.writeSubHeader('Learning Objectives & Milestones')
  cursor.writeParagraph('The objectives map student learning progress across theory, labs, and evaluations:')
  if (program_objectives) {
    program_objectives.forEach(obj => {
      cursor.writeBullet(obj)
    })
  }

  cursor.writeSubHeader('Placement & Career Alignment')
  cursor.writeParagraph('This learning plan qualifies you to pursue placements in the following high-demand roles:')
  if (career_paths) {
    career_paths.forEach(role => {
      cursor.writeBullet(role)
    })
  }

  // ---------------- SECTIONS: SEMESTERS ----------------
  semesters.forEach(sem => {
    cursor.newPage()
    cursor.writeTitle(`Semester ${sem.semester_number}: ${sem.theme}`)
    cursor.writeParagraph(`Focus: ${sem.description || 'Core topics coverage'}. Total units: ${sem.units.length}`)
    cursor.y += 4

    sem.units.forEach(unit => {
      drawUnitCard(cursor, unit)
    })
  })

  // ---------------- PAGE: RECOMMENDED RESOURCES HANDBOOK ----------------
  const books = []
  const videos = []
  const docs = []
  const research = []
  const codebases = []

  semesters.forEach(sem => {
    sem.units.forEach(unit => {
      const res = unit.resources || {}
      if (res.book && !books.includes(res.book)) {
        books.push(res.book)
      }
      if (res.youtube && res.youtube.url && !videos.some(v => v.url === res.youtube.url)) {
        videos.push(res.youtube)
      }
      if (res.google && res.google.url && !docs.some(d => d.url === res.google.url)) {
        docs.push(res.google)
      }
      if (res.research_paper && res.research_paper.url && !research.some(r => r.url === res.research_paper.url)) {
        research.push(res.research_paper)
      }
      if (res.github && res.github.url && !codebases.some(c => c.url === res.github.url)) {
        codebases.push(res.github)
      }
    })
  })

  cursor.newPage()
  cursor.writeTitle('Academic Resources Handbook')
  cursor.writeParagraph('This handbook compiles the recommended reference resources, official documentation guides, video series, and research databases required for this study blueprint. Click the resource titles to open direct digital web references.')
  cursor.y += 4

  const writeCategoryHeader = (title) => {
    cursor.checkSpace(18)
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(12)
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(title.toUpperCase(), cursor.margin, cursor.y)
    cursor.y += 5
    cursor.doc.setDrawColor(226, 232, 240)
    cursor.doc.setLineWidth(0.4)
    cursor.doc.line(cursor.margin, cursor.y, cursor.margin + cursor.width, cursor.y)
    cursor.y += 5
  }

  if (books.length > 0) {
    writeCategoryHeader('1. Core Textbooks & References')
    books.forEach(b => {
      cursor.writeBullet(b)
    })
    cursor.y += 4
  }

  if (videos.length > 0) {
    writeCategoryHeader('2. Video Lectures & Online Courses')
    videos.forEach(v => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(v.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(v.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: v.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  if (docs.length > 0) {
    writeCategoryHeader('3. Official Documentation & Guides')
    docs.forEach(d => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(d.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(d.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: d.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  if (research.length > 0) {
    writeCategoryHeader('4. Accredited Research Databases & Papers')
    research.forEach(r => {
      cursor.checkSpace(16)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(64, 74, 86)
      cursor.doc.text('•  ', cursor.margin, cursor.y)
      
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setTextColor(15, 23, 42)
      cursor.doc.text(r.name, cursor.margin + 5, cursor.y)
      
      cursor.y += 4.5
      
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(9)
      cursor.doc.setTextColor(91, 95, 239)
      const wrappedUrl = cursor.doc.splitTextToSize(r.url, cursor.width - 5)
      wrappedUrl.forEach(l => {
        cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: r.url })
        cursor.y += 4
      })
      cursor.y += 2
    })
    cursor.y += 4
  }

  writeCategoryHeader('5. Practice Portals & Code Playgrounds')
  const practiceLinks = [
    { name: 'LeetCode Placement Practice Platform', url: 'https://leetcode.com' },
    { name: 'HackerRank Academic Assessment Sandbox', url: 'https://hackerrank.com' }
  ]
  if (codebases.length > 0) {
    codebases.forEach(c => {
      practiceLinks.push({ name: `${c.name} (Source Repository)`, url: c.url })
    })
  }

  practiceLinks.forEach(p => {
    cursor.checkSpace(16)
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    cursor.doc.text('•  ', cursor.margin, cursor.y)
    
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(p.name, cursor.margin + 5, cursor.y)
    
    cursor.y += 4.5
    
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(9)
    cursor.doc.setTextColor(91, 95, 239)
    const wrappedUrl = cursor.doc.splitTextToSize(p.url, cursor.width - 5)
    wrappedUrl.forEach(l => {
      cursor.doc.textWithLink(l, cursor.margin + 5, cursor.y, { url: p.url })
      cursor.y += 4
    })
    cursor.y += 2
  })
  cursor.y += 4

  // Return generated PDF object for preview/download workflow
  const filename = `${program_name.replace(/\s+/g, '_')}_Study_Blueprint.pdf`
  return { doc, filename }
}

export const downloadStudentPlannerPDF = async (plannerData, programName, studentName) => {
  if (!plannerData) throw new Error('No planner data provided')

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // ---------------- PAGE 1: COVER PAGE ----------------
  drawPageBorder(doc)

  // Top Accent Band
  doc.setFillColor(91, 95, 239)
  doc.rect(15, 15, 180, 5, 'F')

  // Document Type / Header
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text('STUDY PLANNER SCHEDULE & MILESTONES', 25, 40)

  // Title
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(32)
  doc.setTextColor(15, 23, 42)
  doc.text('STUDY', 25, 55)
  doc.text('PLANNER', 25, 68)

  // Subtitle
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.text('Timeline Strategy, Targets & Day-wise Study Details', 25, 76)

  // Accent Line
  doc.setDrawColor(91, 95, 239)
  doc.setLineWidth(0.8)
  doc.line(25, 82, 75, 82)

  // Specifications
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('SCHEDULE SPECIFICATIONS', 25, 93)

  const specBoxY = 98
  doc.setFillColor(248, 250, 252)
  doc.rect(15, specBoxY, 180, 48, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.rect(15, specBoxY, 180, 48)

  const metaRows = [
    { label: 'Student Name', value: studentName },
    { label: 'Course Title', value: programName },
    { label: 'Plan Duration', value: `${plannerData.totalDays} Days` },
    { label: 'Total Milestones', value: `${plannerData.milestones.length} Milestones` }
  ]

  metaRows.forEach((row, idx) => {
    const col = idx < 2 ? 0 : 1
    const rowInCol = idx % 2
    const x = col === 0 ? 25 : 115
    const yVal = specBoxY + 8 + (rowInCol * 18)

    // Print Label
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(100, 116, 139)
    doc.text(row.label.toUpperCase(), x, yVal)

    // Print Value
    doc.setFont('Helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(15, 23, 42)
    const valText = String(row.value)
    const valLines = doc.splitTextToSize(valText, 70)
    valLines.forEach((line, lineIdx) => {
      doc.text(line, x, yVal + 5 + (lineIdx * 3.5))
    })
  })

  // Summary
  const summaryY = 158
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text('EXECUTIVE SCHEDULE OVERVIEW', 15, summaryY)

  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(15, 162, 195, 162)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(64, 74, 86)
  const summaryText = `This study schedule defines the customized milestone-by-milestone breakdown generated for ${studentName} covering the ${programName} syllabus. Complete the daily tasks, practice labs, and theoretical review items according to the timeline below. Keep this document as a checklist to track and record study achievements.`
  doc.text(summaryText, 15, 168, { align: 'justify', maxWidth: 180 })

  // Footer branding
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('SYLLABIX LEARNER SYSTEM  ·  PLANNER MODULE', 15, 280)
  doc.text(new Date().toLocaleDateString().toUpperCase(), 195, 280, { align: 'right' })

  // Render planner schedule table
  const cursor = new DocumentCursor(doc, `STUDY SCHEDULE: ${programName}`)
  cursor.newPage()
  cursor.writeTitle('Day-wise Study Schedule')
  cursor.writeParagraph(`Below is the customized milestone timeline generated for ${studentName} covering the course units. Complete the targets, review objectives, and execute practical labs accordingly.`)
  cursor.y += 4

  const plannerHeaders = ['Timeline', 'Syllabus Focus', 'Schedule Type', 'Focus & Practical Assignments']
  const plannerRows = plannerData.milestones.map(m => {
    return [
      m.title,
      m.unitName,
      m.type,
      m.description
    ]
  })

  cursor.y = drawTable(doc, cursor.y, plannerHeaders, plannerRows, [28, 40, 32, 80], cursor.margin)

  // Return generated PDF object for preview/download workflow
  const filename = `${programName.replace(/\s+/g, '_')}_Study_Plan.pdf`
  return { doc, filename }
}

export const downloadQuizQuestionPaperPDF = async (courseName, difficulty, quizType, questions) => {
  if (!questions) throw new Error('No quiz questions provided')

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const cursor = new DocumentCursor(doc, `QUESTION PAPER: ${courseName}`)
  
  // Custom cover-like header on first page
  drawPageBorder(doc)
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(15, 23, 42)
  doc.text('EXAMINATION QUESTION PAPER', 15, 28)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(91, 95, 239)
  doc.text(`COURSE: ${courseName.toUpperCase()}`, 15, 35)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(`Difficulty: ${difficulty}  ·  Assessment Mode: ${quizType}  ·  Questions: ${questions.length}`, 15, 41)
  
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(15, 44, 195, 44)

  cursor.y = 50

  questions.forEach((q, idx) => {
    cursor.checkSpace(40)
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(`Question ${idx + 1}  [${q.type}]`, cursor.margin, cursor.y)
    cursor.y += 6

    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    const qLines = cursor.doc.splitTextToSize(q.question, cursor.width)
    const neededHeight = qLines.length * 5.5 + 2
    cursor.checkSpace(neededHeight)
    qLines.forEach(l => {
      cursor.doc.text(l, cursor.margin, cursor.y)
      cursor.y += 5.5
    })
    cursor.y += 3

    if (q.type === 'MCQ' || q.type === 'True/False') {
      const opts = q.options || []
      opts.forEach(opt => {
        cursor.checkSpace(10)
        cursor.doc.setFont('Helvetica', 'normal')
        cursor.doc.setFontSize(11)
        cursor.doc.text(`   [  ]  ${opt}`, cursor.margin, cursor.y)
        cursor.y += 5.5
      })
      cursor.y += 4
    } else if (q.type === 'Fill in the Blanks') {
      cursor.checkSpace(15)
      cursor.doc.setFont('Helvetica', 'italic')
      cursor.doc.setFontSize(11)
      cursor.doc.text('   Answer: _______________________________________________', cursor.margin, cursor.y)
      cursor.y += 8
    } else if (q.type === 'Application Based') {
      cursor.checkSpace(35)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(148, 163, 184)
      cursor.doc.text('   // Write your code implementation below:', cursor.margin, cursor.y)
      cursor.y += 5
      cursor.doc.rect(cursor.margin + 4, cursor.y, cursor.width - 8, 24)
      cursor.y += 28
    } else {
      cursor.checkSpace(25)
      cursor.doc.setFont('Helvetica', 'italic')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(148, 163, 184)
      cursor.doc.text('   Write your response in detail. (Use additional sheets if required).', cursor.margin, cursor.y)
      cursor.y += 10
    }
    cursor.y += 3
  })

  const filename = `${courseName.replace(/\s+/g, '_')}_Question_Paper.pdf`
  doc.save(filename)
}

export const downloadQuizAnswerKeyPDF = async (courseName, difficulty, quizType, questions) => {
  if (!questions) throw new Error('No quiz questions provided')

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const cursor = new DocumentCursor(doc, `ANSWER KEY: ${courseName}`)
  
  // Custom cover-like header on first page
  drawPageBorder(doc)
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(15, 23, 42)
  doc.text('EXAMINATION ANSWER KEY & RUBRICS', 15, 28)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(91, 95, 239)
  doc.text(`COURSE: ${courseName.toUpperCase()}`, 15, 35)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(`Difficulty: ${difficulty}  ·  Assessment Mode: ${quizType}  ·  Questions: ${questions.length}`, 15, 41)
  
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.line(15, 44, 195, 44)

  cursor.y = 50

  questions.forEach((q, idx) => {
    cursor.checkSpace(50)
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(15, 23, 42)
    cursor.doc.text(`Question ${idx + 1}  [${q.type}]`, cursor.margin, cursor.y)
    cursor.y += 6

    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    const qLines = cursor.doc.splitTextToSize(q.question, cursor.width)
    const neededHeight = qLines.length * 5.5 + 2
    cursor.checkSpace(neededHeight)
    qLines.forEach(l => {
      cursor.doc.text(l, cursor.margin, cursor.y)
      cursor.y += 5.5
    })
    cursor.y += 3

    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(16, 185, 129)
    
    let answerText
    if (q.type === 'MCQ' || q.type === 'True/False') {
      const opts = q.options || []
      answerText = `Correct Option: ${opts[q.correct] || ''}`
    } else {
      let cleanExp = q.expectedConcept || ""
      cleanExp = cleanExp
        .replace('[Expected Concept]: ', '')
        .replace('[Expected Word]: ', '')
        .replace('[Expected Essay Concept]: ', '')
        .replace('[Expected Snippet Guide]: ', '')
        .replace('[Expected Rubric]: ', '')
        .replace('[Expected Guide]: ', '')
        .replace('[Expected Case Study Rubric]: ', '')
        .replace('[Expected Interview Guide]: ', '')
      answerText = `Expected Model Concept: ${cleanExp}`
    }

    const ansLines = cursor.doc.splitTextToSize(answerText, cursor.width - 6)
    const ansHeight = ansLines.length * 5.5 + 2
    cursor.checkSpace(ansHeight)
    ansLines.forEach(l => {
      cursor.doc.text(`   ✓  ${l}`, cursor.margin, cursor.y)
      cursor.y += 5.5
    })

    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(10)
    cursor.doc.setTextColor(100, 116, 139)
    
    const expLines = cursor.doc.splitTextToSize(`Explanation: ${q.explanation}`, cursor.width - 6)
    const expHeight = expLines.length * 5 + 2
    cursor.checkSpace(expHeight)
    expLines.forEach(l => {
      cursor.doc.text(`      ${l}`, cursor.margin, cursor.y)
      cursor.y += 5
    })

    if (q.expectedKeywords && q.expectedKeywords.length > 0) {
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setFontSize(9.5)
      cursor.doc.setTextColor(100, 116, 139)
      const keywordText = `      Key Rubric Words: ${q.expectedKeywords.join(', ')}`
      const kwLines = cursor.doc.splitTextToSize(keywordText, cursor.width - 6)
      const kwHeight = kwLines.length * 5 + 1
      cursor.checkSpace(kwHeight)
      kwLines.forEach(l => {
        cursor.doc.text(l, cursor.margin, cursor.y)
        cursor.y += 5
      })
    }

    cursor.doc.setFont('Helvetica', 'italic')
    cursor.doc.setFontSize(9.5)
    cursor.doc.setTextColor(148, 163, 184)
    const tipText = `      Study Rubric Tips: ${q.improvements || "Review unit curriculum references."}`
    const tipLines = cursor.doc.splitTextToSize(tipText, cursor.width - 6)
    const tipHeight = tipLines.length * 5 + 1
    cursor.checkSpace(tipHeight)
    tipLines.forEach(l => {
      cursor.doc.text(l, cursor.margin, cursor.y)
      cursor.y += 5
    })

    cursor.y += 3
  })

  const filename = `${courseName.replace(/\s+/g, '_')}_Answer_Key.pdf`
  doc.save(filename)
}

export const downloadQuizResultReportPDF = async (studentName, courseName, result) => {
  if (!result) throw new Error('No quiz result provided')

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // Cover / Top Header
  drawPageBorder(doc)

  doc.setFillColor(91, 95, 239)
  doc.rect(15, 15, 5, 267, 'F')

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(26)
  doc.setTextColor(15, 23, 42)
  doc.text('QUIZ EVALUATION', 28, 50)
  doc.text('REPORT', 28, 61)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(13)
  doc.setTextColor(100, 116, 139)
  doc.text('Detailed AI-Powered Diagnostic & Performance Audit', 28, 72)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(91, 95, 239)
  doc.text(courseName.toUpperCase(), 28, 100)

  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(64, 74, 86)
  doc.text(`Student Name: ${studentName}`, 28, 112)
  doc.text(`Score: ${result.score} / ${result.total} Questions`, 28, 119)
  doc.text(`Percentage Score: ${result.percentage}%`, 28, 126)
  doc.text(`Correct Responses: ${result.score}`, 28, 133)
  doc.text(`Incorrect Responses: ${result.incorrect}`, 28, 140)

  doc.setFillColor(248, 250, 252)
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.4)
  doc.rect(28, 150, 150, 32, 'F')
  doc.rect(28, 150, 150, 32)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(91, 95, 239)
  doc.text('EVALUATOR GENERAL FEEDBACK:', 32, 156)

  doc.setFont('Helvetica', 'italic')
  doc.setFontSize(10)
  doc.setTextColor(64, 74, 86)
  const feedbackStr = result.feedback || "Good effort. Review missing concepts."
  const fbLines = doc.splitTextToSize(feedbackStr, 142)
  fbLines.forEach((l, idx) => {
    if (idx < 5) doc.text(l, 32, 162 + idx * 5)
  })

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(15, 23, 42)
  doc.text('COMPETENCY PROFILE SUMMARY', 28, 196)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(16, 185, 129)
  doc.text(`Strength Areas:`, 28, 204)
  doc.setFont('Helvetica', 'normal')
  doc.setTextColor(64, 74, 86)
  const strengthsStr = result.strengthAreas ? result.strengthAreas.join(', ') : 'Foundational Concepts'
  doc.text(strengthsStr, 56, 204)

  doc.setFont('Helvetica', 'bold')
  doc.setTextColor(239, 68, 68)
  doc.text(`Improvement Areas:`, 28, 212)
  doc.setFont('Helvetica', 'normal')
  doc.setTextColor(64, 74, 86)
  const weakStr = result.weakAreas ? result.weakAreas.join(', ') : 'None'
  doc.text(weakStr, 62, 212)

  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(148, 163, 184)
  doc.text('SYLLABIX LEARNER SYSTEM  ·  EVALUATION PORTAL', 28, 260)

  const cursor = new DocumentCursor(doc, `QUIZ REPORT: ${courseName}`)
  
  cursor.newPage()
  cursor.writeTitle('Question-by-Question Evaluation Audit')
  cursor.writeParagraph('Each response is graded against syllabus outcomes, design practices, and core keywords:')
  cursor.y += 4

  const reviews = result.reviews || []
  reviews.forEach((q, idx) => {
    cursor.checkSpace(55)
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(15, 23, 42)
    const status = q.isCorrect ? '✓ Correct' : '✗ Incorrect'
    cursor.doc.text(`Q${idx + 1}  [${q.type}]`, cursor.margin, cursor.y)
    
    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    if (q.isCorrect) {
      cursor.doc.setTextColor(16, 185, 129)
    } else {
      cursor.doc.setTextColor(239, 68, 68)
    }
    cursor.doc.text(status, cursor.margin + cursor.width - 25, cursor.y)
    cursor.doc.setTextColor(15, 23, 42)
    cursor.y += 6

    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    const qLines = cursor.doc.splitTextToSize(q.question || '', cursor.width)
    const qHeight = qLines.length * 5.5 + 2
    cursor.checkSpace(qHeight)
    qLines.forEach(l => {
      cursor.doc.text(l, cursor.margin, cursor.y)
      cursor.y += 5.5
    })
    cursor.y += 2

    cursor.doc.setFont('Helvetica', 'bold')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(100, 116, 139)
    cursor.checkSpace(18)
    cursor.doc.text('Student Answer:', cursor.margin, cursor.y)
    cursor.y += 5.5
    cursor.doc.setFont('Helvetica', 'normal')
    cursor.doc.setFontSize(11)
    cursor.doc.setTextColor(64, 74, 86)
    
    let ansStr
    if (q.type === 'MCQ' || q.type === 'True/False') {
      const opts = q.options || []
      ansStr = opts[q.studentAns] || 'No Selection'
    } else if (q.type === 'Application Based') {
      ansStr = q.studentAns?.code || q.studentAns || 'No Answer'
    } else {
      ansStr = q.studentAns || 'No Answer'
    }

    const saLines = cursor.doc.splitTextToSize(ansStr, cursor.width - 6)
    const saHeight = saLines.length * 5.5 + 2
    cursor.checkSpace(saHeight)
    saLines.forEach(l => {
      cursor.doc.text(l, cursor.margin + 4, cursor.y)
      cursor.y += 5.5
    })
    cursor.y += 2

    if (q.details) {
      cursor.doc.setFont('Helvetica', 'bold')
      cursor.doc.setFontSize(10)
      cursor.doc.setTextColor(91, 95, 239)
      
      if (q.type === 'Short Answer') {
        cursor.checkSpace(10)
        cursor.doc.text(`Keyword Similarity: ${q.details.similarity}%`, cursor.margin, cursor.y)
        cursor.y += 5
      } else if (q.type === 'Descriptive' || q.type === 'Long Answer' || q.type === 'Case Study' || q.type === 'Interview Style' || q.type === 'Scenario Based') {
        cursor.checkSpace(10)
        cursor.doc.text(`AI Grader Score: ${q.details.score} / 10`, cursor.margin, cursor.y)
        cursor.y += 5
        cursor.doc.setFont('Helvetica', 'italic')
        cursor.doc.setFontSize(10)
        cursor.doc.setTextColor(100, 116, 139)
        const detailsFeedback = q.details.feedback || "Reviewed against rubric criteria."
        const dFbLines = cursor.doc.splitTextToSize(`Grader Feedback: ${detailsFeedback}`, cursor.width - 8)
        const dFbHeight = dFbLines.length * 5 + 2
        cursor.checkSpace(dFbHeight)
        dFbLines.forEach(l => {
          cursor.doc.text(l, cursor.margin + 4, cursor.y)
          cursor.y += 5
        })
        if (q.details.missing && q.details.missing.length > 0) {
          cursor.doc.setFont('Helvetica', 'bold')
          cursor.doc.setFontSize(10)
          cursor.doc.setTextColor(245, 158, 11)
          const missingText = `Missing Concepts: ${q.details.missing.join(', ')}`
          const misLines = cursor.doc.splitTextToSize(missingText, cursor.width - 8)
          const misHeight = misLines.length * 5 + 2
          cursor.checkSpace(misHeight)
          misLines.forEach(l => {
            cursor.doc.text(l, cursor.margin + 4, cursor.y)
            cursor.y += 5
          })
        }
      }
    }
    cursor.y += 3
  })

  if (result.recommendedTopics && result.recommendedTopics.length > 0) {
    cursor.newPage()
    cursor.writeTitle('AI Study Remediation Roadmap')
    cursor.writeParagraph('Based on your scoring details, prioritize studying the following areas:')
    cursor.y += 4

    result.recommendedTopics.forEach(rec => {
      cursor.checkSpace(35)
      cursor.writeSubHeader(`Prioritize: ${rec.topic}`)
      cursor.writeParagraph(`Reason: ${rec.reason}`)
      cursor.doc.setFont('Helvetica', 'normal')
      cursor.doc.setFontSize(11)
      cursor.doc.setTextColor(100, 116, 139)
      const suggestionLines = cursor.doc.splitTextToSize(`Study Action: ${rec.suggestion}`, cursor.width - 6)
      const sugHeight = suggestionLines.length * 5.5 + 2
      cursor.checkSpace(sugHeight)
      suggestionLines.forEach(l => {
        cursor.doc.text(l, cursor.margin + 4, cursor.y)
        cursor.y += 5.5
      })
      cursor.y += 4
    })
  }

  const filename = `${courseName.replace(/\s+/g, '_')}_Result_Report.pdf`
  doc.save(filename)
}
